service: ws-push-notifications

provider:
  name: aws
  runtime: nodejs10.x
  stage: test
  region: eu-west-1
  environment: # you can define service wide environment variables here
    stage: test
    apiEndpoint: wss://lbqq8qxq96.execute-api.eu-west-1.amazonaws.com
    wsClientsTable: ws-push-notifications-clients-test

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  onConnect:
    handler: src/onConnect/onConnect.handler
    memorySize: 128
    events:
      - websocket: $connect

  onDisconnect:
    handler: src/onDisconnect/onDisconnect.handler
    memorySize: 128
    events:
      - websocket: $disconnect

  pushNotifications:
    handler: src/pushNotifications/pushNotifications.handler
    memorySize: 128
    events:
      - websocket: $default
